import { Event } from '@/shared/EventCard/types';
import { Category } from './types';

export const eventsByCategoryMock: { [key in Category]: Event[] } = {
  week: [
    {
      id: 'dia_mundial_do_rock',
      category: 'a',
      date: 'DOM, 14 JUL • 11:00',
      imageUrl: '/events/pagode_grupo_vibe.png',
      location: 'Praça da Savassi - Belo Horizonte, MG',
      title: 'Dia Mundial do Rock - Praça da Savassi',
    },
    {
      id: 'formatura_2024_rede_formar',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      title: 'Formatura 2024 - Rede Formar',
      imageUrl: '/events/formatura_2024.png',
      location: 'Teatro - Colégio Arnaldo -Belo Horizonte, MG',
    },
    {
      id: 'no_cover',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      title: 'NO COVER 19 - Poly Terror, isso e Shitsunami',
      imageUrl: '/events/no_cover.png',
      location: 'Casa Matriz - Belo horizonte, MG',
    },
    {
      id: 'treinamento_pampulha',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      title: 'Treinamento para a Volta da Pampulha',
      imageUrl: '/events/blade_runner.png',
      location: 'Av. Bernardo de Vasconcelos, 1415 - Belo Horizonte, MG',
    },
    {
      id: 'dia_mundial_do_rock2',
      category: 'a',
      date: 'DOM, 14 JUL • 11:00',
      imageUrl: '/events/pagode_grupo_vibe.png',
      location: 'Praça da Savassi - Belo Horizonte, MG',
      title: 'Dia Mundial do Rock - Praça da Savassi',
    },
    {
      id: 'formatura_2024_rede_formar2',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      title: 'Formatura 2024 - Rede Formar',
      imageUrl: '/events/formatura_2024.png',
      location: 'Teatro - Colégio Arnaldo -Belo Horizonte, MG',
    },
    {
      id: 'no_cover2',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      title: 'NO COVER 19 - Poly Terror, isso e Shitsunami',
      imageUrl: '/events/no_cover.png',
      location: 'Casa Matriz - Belo horizonte, MG',
    },
    {
      id: 'treinamento_pampulha2',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      title: 'Treinamento para a Volta da Pampulha',
      imageUrl: '/events/blade_runner.png',
      location: 'Av. Bernardo de Vasconcelos, 1415 - Belo Horizonte, MG',
    },
  ],
  featured: [
    {
      id: 'ultrassom_microfocado',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Ultrassom Microfocado: O poder do HIFU no Rejuvenescimento',
      imageUrl: '/events/ultrassom_microfocado.png',
      location: 'SaúdeTec Lourdes - Belo Horizonte, MG',
    },
    {
      id: 'jantar_30_anos',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Jantar 30 anos - Prato da Boa Lembrança - Minas Gerais',
      imageUrl: '/events/jantar_30_anos.png',
      location: 'Novotei BH Savassi - Belo Horizonte, MG',
    },
    {
      id: 'colonia_de_ferias',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Colônia de Férias – BoateBus + Parque Guanabara - 20/07',
      imageUrl: '/events/colonia_de_ferias.png',
      location: 'MM Gerdau – Museu das Minas e do Metal - Belo Horizonte, MG',
    },
    {
      id: 'bop_games',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'BOP GAMES 2024 - VISITANTES',
      imageUrl: '/events/bop_games.png',
      location: 'Estádio Mineirão - Belo Horizonte, MG',
    },
    {
      id: 'ultrassom_microfocado2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Ultrassom Microfocado: O poder do HIFU no Rejuvenescimento',
      imageUrl: '/events/ultrassom_microfocado.png',
      location: 'SaúdeTec Lourdes - Belo Horizonte, MG',
    },
    {
      id: 'jantar_30_anos2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Jantar 30 anos - Prato da Boa Lembrança - Minas Gerais',
      imageUrl: '/events/jantar_30_anos.png',
      location: 'Novotei BH Savassi - Belo Horizonte, MG',
    },
    {
      id: 'colonia_de_ferias2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Colônia de Férias – BoateBus + Parque Guanabara - 20/07',
      imageUrl: '/events/colonia_de_ferias.png',
      location: 'MM Gerdau – Museu das Minas e do Metal - Belo Horizonte, MG',
    },
    {
      id: 'bop_games2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'BOP GAMES 2024 - VISITANTES',
      imageUrl: '/events/bop_games.png',
      location: 'Estádio Mineirão - Belo Horizonte, MG',
    },
  ],
  news: [
    {
      id: 'tango_e_boleros',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'TANGOS E BOLEROS CONVIDA TÂNIA ALVES',
      imageUrl: '/events/tango_boleros.png',
      location:
        'Teatro do Centro Cultural Unimed - BH Minas - Belo Horizonte, MG',
    },
    {
      id: 'uma_passagem_para_dois',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Uma passagem para dois',
      imageUrl: '/events/uma_passagem_para_dois.png',
      location: 'Teatro Cultura da Cidade de Nova Repouso - Contagem, MG',
    },
    {
      id: 'cidade_junina',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Cidade Junina - O maior festival de BH',
      imageUrl: '/events/cidade_junina.png',
      location: 'Mirante Beagá - Belo Horizonte, MG',
    },
    {
      id: 'the_lemonheads',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'THE LEMONHEADS NO DISTRITAL',
      imageUrl: '/events/the_lemonheads.png',
      location: 'Distrital - Belo Horizonte, MG',
    },
    {
      id: 'tango_e_boleros2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'TANGOS E BOLEROS CONVIDA TÂNIA ALVES',
      imageUrl: '/events/tango_boleros.png',
      location:
        'Teatro do Centro Cultural Unimed - BH Minas - Belo Horizonte, MG',
    },
    {
      id: 'uma_passagem_para_dois2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Uma passagem para dois',
      imageUrl: '/events/uma_passagem_para_dois.png',
      location: 'Teatro Cultura da Cidade de Nova Repouso - Contagem, MG',
    },
    {
      id: 'cidade_junina2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'Cidade Junina - O maior festival de BH',
      imageUrl: '/events/cidade_junina.png',
      location: 'Mirante Beagá - Belo Horizonte, MG',
    },
    {
      id: 'the_lemonheads2',
      category: 'a',
      date: 'QUA, 15 JUN • 11:00',
      title: 'THE LEMONHEADS NO DISTRITAL',
      imageUrl: '/events/the_lemonheads.png',
      location: 'Distrital - Belo Horizonte, MG',
    },
  ],
  trending: [
    {
      id: 'pagode_com_grupo_vibe',
      category: 'a',
      date: 'QUI, 17 AGO • 12:00',
      imageUrl: '/events/pagode_grupo_vibe.png',
      location: 'Une Bauru - São Paulo, SP',
      title: 'Pagode com Grupo Vibe e Turma do Pagode',
    },
    {
      id: 'caravana_do_bem',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      imageUrl: '/events/caravana_do_bem.png',
      location: 'Sesi São Paulo - Osasco, SP',
      title: 'Caravana do Bem',
    },
    {
      id: 'bruna_louise_bh',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      imageUrl: '/events/bruna_louise.png',
      location: 'BeFly Minascentro - Belo Horizonte, MG',
      title: 'Bruna Louise em BH - Comédia stand up: Ela t´´a correndo atrás',
    },
    {
      id: 'nakka_club',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      imageUrl: '/events/nakka_club.png',
      location: 'Nakka Club - São Paulo - SP',
      title: 'Nakka Club convida LH CHUCRO',
    },
    {
      id: 'pagode_com_grupo_vibe2',
      category: 'a',
      date: 'QUI, 17 AGO • 12:00',
      imageUrl: '/events/pagode_grupo_vibe.png',
      location: 'Une Bauru - São Paulo, SP',
      title: 'Pagode com Grupo Vibe e Turma do Pagode',
    },
    {
      id: 'caravana_do_bem2',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      imageUrl: '/events/caravana_do_bem.png',
      location: 'Sesi São Paulo - Osasco, SP',
      title: 'Caravana do Bem',
    },
    {
      id: 'bruna_louise_bh2',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      imageUrl: '/events/bruna_louise.png',
      location: 'BeFly Minascentro - Belo Horizonte, MG',
      title: 'Bruna Louise em BH - Comédia stand up: Ela t´´a correndo atrás',
    },
    {
      id: 'nakka_club2',
      category: 'a',
      date: 'SAB, 17 AGO • 16:00',
      imageUrl: '/events/nakka_club.png',
      location: 'Nakka Club - São Paulo - SP',
      title: 'Nakka Club convida LH CHUCRO',
    },
  ],
};
